### ISSUE TITLE
No intellisense or error checking 

### ISSUE THREAD

**Issue by ReturnOfTheMac1** [microsoft/vscode-powerquery#107]
Hi - Intellisense/auto complete is not working with my power query extension in VS code.

Syntax highlighting is working, but it won't autocomplete for me.  Also, it won't do any error checking.

Steps I have tried:

- Uninstalling/reinstalling extension
- Rebooting VS code
- Trying other PQ files

My system:
Windows 10, 64 bit, VS Code 1.60.1

Any suggestions?
Thanks

**Comment by ReturnOfTheMac1** [comment]
Hi - it's actually every PQ file that I create - not just one
particular file that has the problem. If I put deliberate errors in the
code it doesn't detect them - see screenshot below.  It should flag no
comma before an In...

Thanks

[image: image.png]

**Comment by ReturnOfTheMac1** [comment]
I did a hard uninstall of VS Code and reinstalled the extension.  It still doesn't work but I got a different error this time which may provide a clue.  Any idea?
![image](https://user-images.githubusercontent.com/48207355/137788068-c074552c-c3db-43b9-a928-7902ae5b89c7.png)

**Comment by JordanBoltonMN** [comment]
Closing as transient and outdated.
