### ISSUE TITLE
troubleshooting, get started 

### ISSUE THREAD

**Issue by SinaMobasheri** [microsoft/vscode-powerquery#123]
Thanks for awesome work <br/>
I'm trying to get started with **Power Query / M Language**, I installed extension via visual studio code market place but unfortunately, it doesn't work, no autocomplete, no formatting... <br/>
is there any other configuration I must do... ? the npm steps are necessary?

**Comment by JordanBoltonMN** [comment]
There shouldn't be any other steps. I have a couple questions. Note, my instructions assume you're on Windows, let me know if that is incorrect.

1)
Can you confirm the extension installed okay by looking under the list of installed extensions? You can get there with `Ctrl + Shift + P` and selecting "Extensions: Show Installed Extensions". Is this entry present for you? 
![image](https://user-images.githubusercontent.com/17787492/148404025-9fb2ebe8-afee-4171-9896-855bfd2e8825.png)

2)
What file extensions have you tried opening? It's currently registered to activate on the following: `.pq .pqm .m .mout`. If you have a plain text (or yet unsaved file) you can manually select what language is active using: `Ctrl + Shift + P`, select "Change Language Mode", and then select "Power Query Formula Language"

**Comment by SinaMobasheri** [comment]
it's installed and i tested in `.m` file, surprisingly I just reinstall it, and it's working...
i guess it was bug in visual studio code..., fortunately, the problem passed
thanks...
