### ISSUE TITLE
support for multiple let-in statements

### ISSUE THREAD

**Issue by LillyBeast** [microsoft/vscode-powerquery#135]
aka, support copy-pasting the whole solution stack from a PBI dataset/dataflow

**Comment by mattmasson** [comment]
Could you provide more detail about how/what is being copy and pasted? Where is the copy action taking place?

**Comment by mattmasson** [comment]
We support the Expression format (single `let` or equivalent M expression) and section document format (which is what Power Query and Dataflows ultimately use behind the scenes). Closing this item, but feel free to reopen with further details.
