### ISSUE TITLE
[Bug] Formatting truncates all comments after let expression

### ISSUE THREAD

**Issue by ninmonkey** [microsoft/vscode-powerquery#144]
**Expected behavior**
To not delete comments when formatting. 

```ts
let y = 1 in y
// stuff
```

**Actual behavior**
Formatting deletes comments at the end of the file.

```ts
let y = 1 in y
```

**To Reproduce**

Using any saved or unsaved files: add comments to the end, then format.

```ts
let
    y = 1
in
    y
    // stuff
```
I tested all combinations of these:

- [x] saved file
- [x] unsaved file
- [x] "powerquery.general.experimental": true,
- [x] "powerquery.general.experimental": false,
- [x] "powerquery.general.mode": "Power Query",
- [x] "powerquery.general.mode": "SDK",

Environment

| Name | Version| 
| - | - |
| VS Code | `1.68.0, 4af164ea3a06f701fe3e89a2bcbb421d2026b68f, x64` |
| Power Query Addon | `PowerQuery.vscode-powerquery@0.1.38` |

I don't think there's anything useful in the log, attached anyway. 
[powerquery.log](https://github.com/microsoft/vscode-powerquery/files/8915289/powerquery.log)

**Comment by JordanBoltonMN** [comment]
Resolved with https://github.com/microsoft/powerquery-formatter/pull/55, still requires a new release to be made.
