### ISSUE TITLE
Cannot find the name 'Python.Execute'

### ISSUE THREAD

**Issue by tonycesar** [microsoft/vscode-powerquery#173]
**Is your feature request related to a problem? Please describe.**
I try to work with Python script into VS Editor, but is not supported
**Describe the solution you'd like**
I think that basic, the best solution is add as Function into dictionary

**Describe alternatives you've considered**
A great feature will be show the code python into this fuction of a beauty format like editor in PowerBI. (#(lf) is the char of \n into code expresed into a custom python script embebed into a string)

**Additional context**
Here an example:

```
  let
      Origen = Python.Execute("import pandas as pd#(lf)data = [['Alex',10],['Bob',12],['Clarke',13]]#(lf)df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)#(lf)print (df)"),
      df1 = Origen{[Name="df"]}[Value],
      #"Tipo cambiado" = Table.TransformColumnTypes(df1,{{"Name", type text}, {"Age", Int64.Type}})
  in
      #"Tipo cambiado"
```

**Comment by mattmasson** [comment]
For context - the tools we're using to generate the [library symbol files](https://github.com/microsoft/vscode-powerquery/blob/master/server/src/library/standard/standard-enUs.json) include a subset of connectors... in fact, the symbols we include should pretty much match what is listed in the official [Power Query M function reference](https://learn.microsoft.com/en-us/powerquery-m/power-query-m-function-reference).

Including more symbols is doable, it'll just require some changes to the tools we're using.

If we're able to make these changes, we should probably add all of the functions available in a default installation of Power BI Desktop (which includes Python and about 100 other connectors).

**Comment by mattmasson** [comment]
Tracked by #206
