### ISSUE TITLE
[BUG] Document Symbols aren't working

### ISSUE THREAD

**Issue by mattmasson** [microsoft/vscode-powerquery#177]
**Expected behavior**
Outline treeview should show document symbols for pq files. 

**Actual behavior**
"No symbols found in document 'test.pq'

**To Reproduce**
Open a section document and expand the OUTLINE tree view.

This also seems to be the cause of one of the UI test failures.

**Comment by JordanBoltonMN** [comment]
Sort of resolved with #178 . I need to investigate why debouncing that API caused this regression.
