### ISSUE TITLE
[BUG] Excel.CurrentWorkbook raises UnknownIdentifier error

### ISSUE THREAD

**Issue by CABrinegar** [microsoft/vscode-powerquery#180]
**Expected behavior**
Excel.CurrentWorkbook should be recognized as a valid identifier.

**Actual behavior**
Using Excel.CurrentWorkbook raises the following error:
`Cannot find the name 'Excel.CurrentWorkbook', did you mean 'Excel.Workbook'? powerquery(Error.UnknownIdentifier)`

**To Reproduce**
Example script:
```
let
    foo = Excel.CurrentWorkbook()
in
    foo
```

**Additional context**
This function is documented at https://learn.microsoft.com/en-us/powerquery-m/excel-currentworkbook

**Comment by CABrinegar** [comment]
Fixed by PR https://github.com/microsoft/vscode-powerquery/pull/181

**Comment by mattmasson** [comment]
Thanks - we use an automated (internal) process to dump the symbols and produce these files, so I don't think we'll merge PR #181. But we'll fix the bug that was preventing Excel.CurrentWorkbook from being emitted along with the other symbols.

**Comment by PJSoftware** [comment]
I am also waiting on this issue to be resolved -- or I was, a couple of months back when I first found it. Another symbol I'm using which has the same problem is:

Cannot find the name 'AutodeskConstructionCloud.Contents'.powerquery(Error.UnknownIdentifier)

I'm sure the resolution will be the same, but I'm adding it here so you have an additional symbol to test for when fixing your symbol-dumping bug.

**Comment by patlachance** [comment]
> Thanks - we use an automated (internal) process to dump the symbols and produce these files, so I don't think we'll merge PR #181. But we'll fix the bug that was preventing Excel.CurrentWorkbook from being emitted along with the other symbols.

@mattmasson any idea of when it could be fixed?

**Comment by mattmasson** [comment]
tracked by #206

**Comment by mattmasson** [comment]
tracked by #206
