### ISSUE TITLE
Unable to pass record that contain a date as a parameter from query.pq file to .pq file 

### ISSUE THREAD

**Issue by Canadug** [microsoft/vscode-powerquery#182]
PROBLEM

I wrote a test query that contained a record that I passed to my main function and found that if the record contains a date data type you will get a credential error.

STEPS TO RECREATE

1. Use the **Hello World** example outlined [here](https://learn.microsoft.com/en-us/power-query/power-query-sdk-vs-code)
2. In the **query** file, use something like this:

```
let
  MyRecord =  [ StartDate = Date.FromText("2022-01-02") ],
  Result = MyConnector.Contents( MyRecord )
in
  Result
```
3. In the **pq** file, alter the Hello World example as follows:
```
...
shared MyConnector.Contents = ( MyRecord as record ) =>
let
    Result = MyRecord[StartDate]
in
    Result;
...
```

4. Run the "Set credential" task
5. With the query file open, run the "Evaluate current file" task

EXPECTED OUTCOME

The query should run with the date being outputted

ACTUAL OUTCOME

The PQTest fails with the following error:

`Credentials are required to connect to the PQExtensionSample2 source. (Source at {"MyRecord":{"StartDate":"2022-01-02"}}.)`

WORK AROUND

If you set the data type to text, it query will run as expected.

e.g. `MyRecord =  [ StartDate = "2022-01-02" ],`

**Comment by mattmasson** [comment]
This is more of a question for the vscode-powerquery-sdk project. 
But to clarify, this should be possible. The error you're getting indicates that you're missing a credential. By default, any required parameters are factored into your credential. See: https://learn.microsoft.com/en-us/power-query/handling-resource-path

What is not supported in the Power Query UI is having a `record` parameter as input (other than having a final optional `options` record). So it is recommended that any required input properties are primitive types (number, text, etc).
