### ISSUE TITLE
[BUG] PowerPlatForm.Dataflows function not recognized by language parser

### ISSUE THREAD

**Issue by FireFighter1017** [microsoft/vscode-powerquery#203]
**Expected behavior**
Function 'PowerPlatform.Dataflows([])' should not be reported as a problem

**Actual behavior**
The function is reported as a problem with following message:
`Cannot find the name 'PowerPlatform.Dataflows'.`

**To Reproduce**
Please include the following:
-   (Required) The Power Query script that triggers the issue.
    `let
        Source = PowerPlatform.Dataflows([]){[Id = "Workspaces"]}[Data],
        Workspace = Source{[workspaceId=WS_DATA_CONVERSION]}[Data],
        Dataflow = Workspace{[dataflowId=DF_PM_1_EXTRACT]}[Data],
        Entity = Dataflow{[entity="SGDOCMP"]}[Data]
    in
        Entity`

-   (Required) Any non-default settings used in the API call(s) which trigger the issue.
    Not an API call as far as I'm concerned

**Additional context**

**Comment by FireFighter1017** [comment]
Same thing happens with function `PowerBI.Dataflows()`

**Comment by CsanizAZ** [comment]
Same thing happens with function `Snowflake.Databases()`
@JordanBoltonMN Should we be opening these as separate issues?

**Comment by mattmasson** [comment]
tracked by #206
