### ISSUE TITLE
[BUG]Runtime Status: Not yet activated

### ISSUE THREAD

**Issue by EmmaWang22** [microsoft/vscode-powerquery#208]
Description:
I am encountering an issue with the activation of the "Power Query M Formula" plugin in Visual Studio Code. When attempting to use the plugin, I receive the message "Not yet activated." It seems that the plugin fails to activate properly and does not provide any status information.

Steps to Reproduce:

Install the "Power Query M Formula" plugin in Visual Studio Code.
Open a file containing DAX code.
Attempt to format the DAX code using the plugin's formatting feature.
Expected Behavior:
The plugin should activate successfully and provide the formatting feature for DAX code.

Actual Behavior:
The plugin fails to activate, and the message "Not yet activated" is displayed.

Additional Information:

I have tried reloading the window and restarting Visual Studio Code, but the issue persists.
My Visual Studio Code version is [ 1.86.2 (user setup)], and I am using the latest version of the "Power Query M Formula" plugin.
I have checked for any error messages in the output window, but none are displayed.
System Information:

Version: 1.86.2 (user setup)
Chromium: 118.0.5993.159
OS: Windows_NT x64 10.0.19045
I appreciate your assistance in resolving this issue. Please let me know if you require any further information.

Thank you,
Emma

**Comment by mattmasson** [comment]
The vscode-powerquery extension only supports the M language at this time. DAX support would need to come through a different VS Code extension.
