### ISSUE TITLE
Null coalescing operator is not accepted

### ISSUE THREAD

**Issue by SpyrosMauro** [microsoft/vscode-powerquery#56]
Power Query includes a hidden null coalescing operator: ??

This syntax is accepted:
`Value??OtherValue`

It would be nice if this was accepted by the parser, which throws the problem `"Expected to find a right parenthesis ... but a question mark was found instead powerquery(Error.Parse) [7,70]"`

See more [here](https://social.technet.microsoft.com/Forums/en-US/180757fe-47c0-4377-bb04-9cccadf4537b/null-coalescing-operator-?forum=powerquery)

**Comment by mattmasson** [comment]
Tracked in the parser repo - https://github.com/microsoft/powerquery-parser/issues/173

This operator was a recent addition to the M language. I'm not sure it is has been fully documented or is available in all Power Query environments, but we should have it added to the current parser.

**Comment by CurtHagenlocher** [comment]
This isn't supported for folding yet, unfortunately. I was going to hold off on documenting it until that was possible.
