### ISSUE TITLE
Using Power Query VS Code plugin from other tools

### ISSUE THREAD

**Issue by erapade** [microsoft/vscode-powerquery#64]
Could you just briefly elaborate of the possibilities to use the Power Query CS Code plugin server from other tools. I'm thinking mostly about the Tabular Editor: https://github.com/otykier/TabularEditor

**Comment by mattmasson** [comment]
The [powerquery-language-services](https://github.com/microsoft/powerquery-language-services) project provides the intellisense functionality used by this VS Code extension. It relies on [powerquery-parser](https://github.com/microsoft/powerquery-parser) for its underlying M parsing. Both projects are typescript/javascript based.
