### ISSUE TITLE
Quoted Identifier error: hover failed with message: InvariantError: should never be reached

### ISSUE THREAD

**Issue by ninmonkey** [microsoft/vscode-powerquery#65]
Description
----
Hovering over function signatures has an error when the identifier is not correct. 

Expected Behavior
----
![image](https://user-images.githubusercontent.com/3892031/94205469-fa813300-fe88-11ea-9141-2a706fd2064e.png)

Actual Behavior
----

It doesn't silently log like other errors. You get a popup: 
![image](https://user-images.githubusercontent.com/3892031/94205903-d70ab800-fe89-11ea-9d21-b7e85e9dc41c.png)

```log
[Trace - 5:12:28 PM] Received response 'textDocument/hover - (40)' in 0ms. Request failed: Request textDocument/hover failed with message: InvariantError: should never be reached (-32603).
[Error - 5:12:28 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: InvariantError: should never be reached
  Code: -32603 
```
Steps to reproduce
----
Create a new file, then hover over the Numbers function.
```pq
let
   #"Stuff" = List.Numbers(1, 1, 1)
in
    #"Stuff
```

Fix
----
Close the quote on the final identifier.

```pq
let
   #"Stuff" = List.Numbers(1, 1, 1)
in
    #"Stuff"
```
[error log - short.log](https://github.com/microsoft/vscode-powerquery/files/5279487/error.log.-.short.log)

**Comment by mattmasson** [comment]
This seems to be fixed with #68
