### ISSUE TITLE
Method signature page 2 is detected, UI resets to page 1

### ISSUE THREAD

**Issue by ninmonkey** [microsoft/vscode-powerquery#71]
# About

Tooltips showing the current method signature sticks on page 1

When `Table.AddColumn` includes the optional parameter `columnType` it underlines the 4th parameter correctly.
But it's hidden because the tooltip should be on page 2. (I thought a previous version swapped pages)

# Behavior 

The video shows when the 4th parameter exists:

1. It doesn't switch to page 2
2. If you manually set it to page 2, then move the cursor left -- it jumps back to page 1

https://user-images.githubusercontent.com/3892031/110214493-69b47780-7e6a-11eb-8989-d6cdacb47403.mp4

# Environments

Name | Version
------------ | -------------
extension | PowerQuery.vscode-powerquery@0.1.18
code | 1.53.2, 622cb03f7e070a9670c94bae1a45d78d7181fbd4, x64
code-insiders | 1.55.0-insider, 04770364fdc1bebeca9d1a257df2cacce06b35d6, x64

I noticed [releases](https://github.com/microsoft/vscode-powerquery/releases/) is on v0.1.16, I'm using the regular [marketplace version](https://marketplace.visualstudio.com/items?itemName=PowerQuery.vscode-powerquery)

# Code

```powerquery
let
    Source = ...,
    #"Select Active" = Table.SelectRows( Source, each [Active] = true),
    #"Add Col Date" = Table.AddColumn(
        #"Select Active", "Date", each DateTime.Date( [Datetime] ), type date )

in
    #"Add Col Date"
```

**Comment by JordanBoltonMN** [comment]
Resolved in #77
