### ISSUE TITLE
Running Queries within VS Code

### ISSUE THREAD

**Issue by d4hines** [microsoft/vscode-powerquery#72]
Hello!

Is it possible to run PowerQuery programs from within VS Code? That is, is there some open source engine that we could use and integrate with the editor for the kind of rich live editing experience we get in Excel but with the comforts of the other tooling that VS Code provides (Git, Vim bindings, etc. etc.)? This would truly be the best of both worlds as far as I'm concerned.

Thanks!

**Comment by mattmasson** [comment]
Not today, but we're actively working on a way to provide this functionality in the context of developing and testing Custom Connectors for Power Query.

**Comment by bgribaudo** [comment]
> Not today, but we're actively working on a way to provide this functionality in the context of developing and testing Custom Connectors for Power Query.

This is exciting! Very interested to see what develops here.

**Comment by JordanBoltonMN** [comment]
I'll be marking this as closed since as of today there's no way to run queries.
