### ISSUE TITLE
Timeline for Replacement of Visual Studio SDK

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery#97]
Hi,

In the Q&A section for the current Visual Studio [Power Query SDK](https://marketplace.visualstudio.com/items?itemName=Dakahn.PowerQuerySDK&ssr=false#qna), there's a response from Microsoft dated 2021-05-07 saying:

> We aren't planning on making further updates to the Visual Studio based Power Query SDK. All future development efforts are focused on enabling a similar experience in VS Code.

This is exciting! :-)

Do you have any sense on the timeline as to when the similar VSCode experience will be available? From the outside perspective, tooling for custom connector development currently seems to be in limbo--for example, the existing SDK hasn't been updated since August 2019, so is using an out-of-date M engine version. It would be neat to have some sense for when a currently-updated tool will be available.

Thanks,
Ben

**Comment by bgribaudo** [comment]
Thanks for the update, @JordanBoltonMN!

**Comment by JordanBoltonMN** [comment]
Since this is a timeline post and not currently an actionable issue I'll be closing this for now. I can't give any details other some of the high priority issues are nearing the finish line which hopefully will free the cycles to progress on this feature.

**Comment by JordanBoltonMN** [comment]
See #127
