### ISSUE TITLE
[BUG] Type "any" not considered a superset of other types

### ISSUE THREAD

**Issue by JDCAce** [microsoft/vscode-powerquery#98]
**Expected behavior**
When passing a value of a specific type (e.g., `number`, `text`, `record`) to a function which expects a value with a type of `any`, it should be accepted without raising an `Error.InvokeArgumentTypeMismatch` error.

![image](https://user-images.githubusercontent.com/758002/127753402-873b7cdc-7e5e-4bf2-b002-67f989b7f860.png)

![image](https://user-images.githubusercontent.com/758002/127753384-78d702cb-b24e-437f-a748-fa4cffec91d0.png)

**Actual behavior**
An `Error.InvokeArgumentTypeMismatch` error is raised when a value is passed to a function which expects a value of type `any` unless the passed value is specifically cast to type `any` with `... as any`. This occurs with both literals and variables.

![image](https://user-images.githubusercontent.com/758002/127753436-f91785b6-3b0d-452d-85d5-2cfcbab3779c.png)

![image](https://user-images.githubusercontent.com/758002/127753290-0636d068-b1bf-4845-a12c-2ca0a1b943b9.png)

Note: The function expects two values of type `any`. To illustrate the issue, I have explicitly cast one of the two to `any`. 

**To Reproduce**
Insert the following query in Visual Studio Code running this Power Query extension, version 0.1.20:
```
let
    typeError = #table({"Column 1", "Column 2"}, {{1, 2}} as any)
in
    typeError
```

**Additional context**
I believe this bug was introduced with version 0.1.20, released July 14. I do not believe this bug existed when I first began using this extension in June.

**Comment by JordanBoltonMN** [comment]
Thanks for the report. Resolved in #96, and will be updating the extension shortly.
